ido-tth/main/default/objects/tth_Booking__c/tth_Booking__c.object-meta.xml
<CustomObject>
    <description>Top level object that represents the planning aspect of a particular portion within a trip.  Once a booking is completed/paid for/ticketed, a reservation (separate object) should be created to represent the actual instance(s) of the elements within the booking.</description>
    <label>Booking</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ido-tth/main/default/objects/tth_Booking__c/fields/tth_Account__c.field-meta.xml
<CustomField>
    <fullName>tth_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This isn&#39;t really a field that is actually used, rather it is to provide a bit of a work around when using PersonAccounts in combo with SFDX data import. There&#39;s a few workflows hooked into this field to populate the Contact/Traveler Master Detail</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DO_NOT_USE_Bookings</relationshipLabel>
    <relationshipName>DO_NOT_USE_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking__c/fields/tth_Booking_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>tth_Booking_Confirmation__c</fullName>
    <description>For cases where the term Record Locator is not appropriate and the PNR format is not appropriate (e.g. Hotels will have a Booking Reference/Confirmation number of some sort)</description>
    <label>Booking Confirmation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking__c/fields/tth_Record_Locator__c.field-meta.xml
<CustomField>
    <fullName>tth_Record_Locator__c</fullName>
    <description>Commonly referred to as: PNR, Booking Reference, Agency Locator, CRS, etc</description>
    <label>Record Locator</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking__c/fields/tth_Ticket_ID__c.field-meta.xml
<CustomField>
    <fullName>tth_Ticket_ID__c</fullName>
    <description>Ticket confirmation/identification number</description>
    <label>Ticket ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking__c/fields/tth_Traveler__c.field-meta.xml
<CustomField>
    <fullName>tth_Traveler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Traveler</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/tth_Booking_ReservationSettings__mdt.object-meta.xml
<CustomObject>
    <description>Various settings for the TTH Booking/Reservation functionality.  Includes settings for the following custom objects: Trip, Booking, Reservation</description>
    <label>tth_Booking/ReservationSettings</label>
    <pluralLabel>tth_Booking/ReservationSettings</pluralLabel>
</CustomObject>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/Booking_Reference_Length__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference_Length__c</fullName>
    <defaultValue>9</defaultValue>
    <label>Booking Reference Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/BookingTriggersDisabled__c.field-meta.xml
<CustomField>
    <fullName>BookingTriggersDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should be used by APEX Triggers to check whether they should execute</description>
    <label>BookingTriggersDisabled</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/Generate_Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Generate_Booking_Reference__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines whether the Booking Reference field on the Booking custom object should be populated</description>
    <label>Generate Booking Reference</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/Generate_International_Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Generate_International_Ticket_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should the ticket number on the Reservation object be generated?</description>
    <label>Generate International Ticket Number</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/Generate_Record_Locator__c.field-meta.xml
<CustomField>
    <fullName>Generate_Record_Locator__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Should the system auto generate a 6 digit Record Locator?</description>
    <label>Generate Record Locator</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/International_Airline_Number__c.field-meta.xml
<CustomField>
    <fullName>International_Airline_Number__c</fullName>
    <description>Used when generating the Ticket number on the Reservation object. See full list of airlines here: https://www2.arccorp.com/participatingcarriers/#/</description>
    <label>International Airline Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/InternationalTicketLength__c.field-meta.xml
<CustomField>
    <fullName>InternationalTicketLength__c</fullName>
    <defaultValue>10</defaultValue>
    <description>When generating the ticket number on the Reservation, how long should it be NOT including the International Airline Number</description>
    <label>InternationalTicketLength</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/Record_Locator_Length__c.field-meta.xml
<CustomField>
    <fullName>Record_Locator_Length__c</fullName>
    <defaultValue>6</defaultValue>
    <label>Record Locator Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ido-tth/main/default/classes/tthBookingTriggerHandler.cls
public class tthBookingTriggerHandler implements ITriggerHandler {

  private tth_Booking_ReservationSettings__mdt metaSettings = null;
  public tthBookingTriggerHandler() {
    metaSettings = tth_BookingReservationUtils.getBookingMetadataSettings();
  }

  /*
    Allows unit tests (or other code) to disable this trigger for the transaction
    To stop this trigger from firing while in a unit test, I could just add the following code to the test:
    AccountTriggerHandler.TriggerDisabled = true;
  */
  public static Boolean TriggerDisabled = false;

  /*
    Checks to see if the trigger has been disabled. For example, you could check a custom setting here.
    In this example, a static property is used to disable the trigger.
    In a unit test, you could use AccountTriggerHandler.TriggerDisabled = true to completely disable the trigger.
  */
	public Boolean IsDisabled() {
    /*
      Use the option below if you set up Custom Settings to controll Triggers
    */
    if(metaSettings != null) {
       return metaSettings.BookingTriggersDisabled__c;
     }
    return TriggerDisabled;
    }


	public void BeforeInsert(List<SObject> newItems) {
    caterForSFDXPersonAccounts((tth_Booking__c[])newItems);
    if (metaSettings != null && metaSettings.Generate_Record_Locator__c == true) {
        generateRecordLocator((tth_Booking__c[])newItems);
    }
    if (metaSettings != null && metaSettings.Generate_International_Ticket_Number__c == true) {
      generateTicketNumber((tth_Booking__c[])newItems);
    }
    if (metaSettings != null && metaSettings.Generate_Booking_Reference__c == true) {
      generateBookingReference((tth_Booking__c[])newItems);
    }
  }

	public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {}

	public void BeforeDelete(Map<Id, SObject> oldItems) {}

	public void AfterInsert(Map<Id, SObject> newItems) {}

	public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {}

	public void AfterDelete(Map<Id, SObject> oldItems) {}

	public void AfterUndelete(Map<Id, SObject> oldItems) {}

    /**
     *
     *
     *
    **/
    private void generateRecordLocator(List<tth_Booking__c> bookings){
      for(tth_Booking__c curBooking : bookings) {
        String newRecLocator = tth_BookingReservationUtils.generateRecordLocator((Integer)metaSettings.Record_Locator_Length__c);

        //ensure it is unique
        boolean isUniqueRecLocator = false;
        tth_Booking__c bookCheck;
        while(isUniqueRecLocator == false) {
          try {
            bookCheck = [select ID FROM tth_Booking__c WHERE tth_Record_Locator__c =: newRecLocator];
          } catch (Exception ex) {
            // no record found
            bookCheck = null;
          }

          if (bookCheck == null) {
            // No Booking found with same locator, can exit the loop
            isUniqueRecLocator = true;
          } else {
            // Booking found with same Reference so need to try again
            isUniqueRecLocator = false;
          }
        }
        curBooking.tth_Record_Locator__c = newRecLocator;
      }
    }

    /**
     *
     *
     *
    **/
    private void generateTicketNumber(List<tth_Booking__c> reservations){
      for(tth_Booking__c curReservation : reservations) {
        String newTicketNumber = tth_BookingReservationUtils.generateInternationalTicketNumber((Integer)metaSettings.InternationalTicketLength__c);

        if (metaSettings != null && metaSettings.International_Airline_Number__c != '') {
          curReservation.tth_Ticket_ID__c = metaSettings.International_Airline_Number__c + ' ';
        }
        curReservation.tth_Ticket_ID__c += newTicketNumber;
      }
    }

    /**
     *
     *
     *
    **/
    private void generateBookingReference(List<tth_Booking__c> reservations){
      String newBookingReference = '';
      for(tth_Booking__c curReservation : reservations) {
         newBookingReference = tth_BookingReservationUtils.generateBookingReference((Integer)metaSettings.Booking_Reference_Length__c);

        curReservation.tth_Booking_Confirmation__c = newBookingReference;
      }
    }


    /*
      This is mainly to fill a gap in the way SalesforceDX imports data in combo
      with using PersonAccounts and the relationship being on the Contact sObject
     */
    private void caterForSFDXPersonAccounts(tth_Booking__c[] bookingList){
      // Check if the Account field is filled out on the Trip and the contact is NOT
      // Look up the account that is linked and if it is a PersonAccount,
      // grab the Contact ID and update Trip Record with that ID
      for(tth_Booking__c curBooking : bookingList) {
        if (curBooking.tth_Account__c != null && curBooking.tth_Traveler__c == null) {
          Account linkedAcnt = [SELECT ID, PersonContactId, isPersonAccount FROM account where id =: curBooking.tth_Account__c];
          if (linkedAcnt.isPersonAccount) {
            curBooking.tth_Traveler__c = linkedAcnt.PersonContactId;
          }
        }
      }
    }

}