ido-tth/main/default/objects/Contact/fields/tth_Next_Trip__c.field-meta.xml
<CustomField>
    <fullName>tth_Next_Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the traveler&#39;s next trip/destination?</description>
    <label>Next Trip</label>
    <referenceTo>tth_Trip__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

ido-tth/main/default/objects/tth_Trip__c/tth_Trip__c.object-meta.xml
<CustomObject>
    <description>Top level object that represents all booking channels as well as travel modes for an end to end customer trip</description>
    <label>Trip</label>
    <nameField>
        <displayFormat>TRIP {0}</displayFormat>
        <label>Trip ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ido-tth/main/default/objects/tth_Trip__c/fields/tth_Trip_Destination__c.field-meta.xml
<CustomField>
    <fullName>tth_Trip_Destination__c</fullName>
    <description>What is the destination city for this trip?</description>
    <label>Destination City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ido-tth/main/default/classes/tth_EnhanceWithTripDestination.cls
global class tth_EnhanceWithTripDestination {

  private static String CONTACT_PREIX = '003';
  private static String ACCOUNT_PREFIX = '001';
  private static String CHAT_TRANS_PREFIX = '570';


  global class DataContainer {
      @InvocableVariable
      public string recordId;

      @InvocableVariable
      public List<Recommendation> recommendations;
  }


  @InvocableMethod(label='Enhance with Next Destination' description='Looks at the travelers next trip destination and appends "in location" to the end of each recommendation')
  global static List<List<Recommendation>> enhanceWithDestination(List<DataContainer> inputData) {
      List<List<Recommendation>> outputs = new List<List<Recommendation>>();
      List<Recommendation> editedRecomendations = new List<Recommendation>();

      for (DataContainer curInput : inputData) {
        String nextTripLocation = getNextTripLocation(curInput.recordId);
        List<Recommendation> recommendations = curInput.recommendations;

        for(Recommendation curRec : recommendations) {
          curRec.Description += ' in ' + nextTripLocation;
          editedRecomendations.add(curRec);
        }
      }
      outputs.add(editedRecomendations);
      return outputs;
  }


  private static String getNextTripLocation(String recordId){
    String contactId;
    if ( recordId.startsWithIgnoreCase(ACCOUNT_PREFIX) ) {
      System.debug('This is an account/person account record');
      Contact accountContact = [SELECT id FROM Contact WHERE AccountId = :recordId LIMIT 1];
      contactId = accountContact.ID;
    } else if ( recordId.startsWithIgnoreCase(CONTACT_PREIX) ) {
      System.debug('This is a contact record');
      contactId = recordId;
    } else if ( recordId.startsWithIgnoreCase(CHAT_TRANS_PREFIX) ) {
      System.debug('This is a LiveChat Transcript record');
      LiveChatTranscript chatTrans = [SELECT ContactId FROM LiveChatTranscript WHERE Id = :recordId LIMIT 1];
      contactId = chatTrans.ContactId;
    } else {
      System.debug('No idea what kind of object this is, I was anticipating either an Account or Contact');
    }
    tth_Trip__c nextTrip = [SELECT tth_Trip_Destination__c FROM tth_Trip__c where ID IN (SELECT tth_Next_Trip__c FROM Contact WHERE ID = :contactId) LIMIT 1];
    return nextTrip.tth_Trip_Destination__c;
  }


}