ido-tth/main/default/objects/Contact/fields/tth_Trip_Stage__c.field-meta.xml
<CustomField>
    <fullName>tth_Trip_Stage__c</fullName>
    <defaultValue>&quot;PreTrip&quot;</defaultValue>
    <description>Demo triggering field - Used to show where within the demo journey we are.  Used to change the &quot;state&quot; of the demo and may impact items such as Component Visibility, Trigger process builder to create needed records, provides context to the Chatbot for context specific menus</description>
    <label>Trip Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>tth_Travel_Stage</valueSetName>
    </valueSet>
</CustomField>

ido-tth/main/default/objects/Contact/fields/tth_Trip_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>tth_Trip_Sub_Stage__c</fullName>
    <description>Defines the sub stage of the travelers journey</description>
    <label>Trip Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>tth_Trip_Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Trip_Sub_Stage</valueSetName>
    </valueSet>
</CustomField>

ido-tth/main/default/objects/Recommendation/fields/tth_Trip_Stage__c.field-meta.xml
<CustomField>
    <fullName>tth_Trip_Stage__c</fullName>
    <description>Represents the current traveler&#39;s trip stage. It is a text field b/c NBA does not support multiselect picklists so if it applies to multiple recommendations, use a comma separated list and ensure Strategy filters leverage the CONTAINS formula function</description>
    <label>Trip Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ido-tth/main/default/objects/Recommendation/fields/tth_Trip_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>tth_Trip_Sub_Stage__c</fullName>
    <description>This is currently a text field because multi select picklists are supported yet by NBA Strategy Builder</description>
    <label>Trip Sub Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking__c/tth_Booking__c.object-meta.xml
<CustomObject>
    <description>Top level object that represents the planning aspect of a particular portion within a trip.  Once a booking is completed/paid for/ticketed, a reservation (separate object) should be created to represent the actual instance(s) of the elements within the booking.</description>
    <label>Booking</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ido-tth/main/default/objects/tth_Booking__c/fields/tth_Booking_Type__c.field-meta.xml
<CustomField>
    <fullName>tth_Booking_Type__c</fullName>
    <label>Booking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>tth_Service_Type</valueSetName>
    </valueSet>
</CustomField>

ido-tth/main/default/objects/tth_Booking__c/fields/tth_Trip__c.field-meta.xml
<CustomField>
    <fullName>tth_Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What trip is this booking related to?</description>
    <label>Trip</label>
    <referenceTo>tth_Trip__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

ido-tth/main/default/objects/tth_Trip__c/tth_Trip__c.object-meta.xml
<CustomObject>
    <description>Top level object that represents all booking channels as well as travel modes for an end to end customer trip</description>
    <label>Trip</label>
    <nameField>
        <displayFormat>TRIP {0}</displayFormat>
        <label>Trip ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ido-tth/main/default/globalValueSets/Trip_Sub_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Future Booking</fullName>
        <default>true</default>
        <label>No Future Booking</label>
    </customValue>
    <customValue>
        <fullName>Has Future Booking</fullName>
    </customValue>
    <customValue>
        <fullName>Smooth Travels</fullName>
    </customValue>
    <customValue>
        <fullName>Experiencing Disruption</fullName>
    </customValue>
    <customValue>
        <fullName>Positive Sentiment</fullName>
    </customValue>
    <customValue>
        <fullName>Negative Sentiment</fullName>
    </customValue>
    <description>What sub stage is the traveler on within their trip. Is dependent picklist of the Trip Stage field</description>
    <masterLabel>Trip Sub-Stage</masterLabel>
</GlobalValueSet>

ido-tth/main/default/globalValueSets/tth_Service_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Flight</fullName>
    </customValue>
    <customValue>
        <fullName>Hotel</fullName>
    </customValue>
    <customValue>
        <fullName>Car</fullName>
    </customValue>
    <customValue>
        <fullName>Rail</fullName>
    </customValue>
    <customValue>
        <fullName>Bus</fullName>
    </customValue>
    <customValue>
        <fullName>Ferry</fullName>
    </customValue>
    <customValue>
        <fullName>Restaurant</fullName>
    </customValue>
    <customValue>
        <fullName>Activity</fullName>
    </customValue>
    <customValue>
        <fullName>Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Transport</fullName>
    </customValue>
    <customValue>
        <fullName>Accomodation</fullName>
    </customValue>
    <description>What are the types of generic services used across all travel and hospitality?</description>
    <masterLabel>Service Type</masterLabel>
</GlobalValueSet>

ido-tth/main/default/globalValueSets/tth_Travel_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PreTrip</fullName>
        <default>true</default>
        <label>PreTrip</label>
    </customValue>
    <customValue>
        <fullName>OnTrip</fullName>
    </customValue>
    <customValue>
        <fullName>PostTrip</fullName>
    </customValue>
    <description>What part of the guest journey is the demo currently within</description>
    <masterLabel>Travel Stage</masterLabel>
</GlobalValueSet>

ido-tth/main/default/classes/tth_NBA_Generate_TripDisruption.cls
//TODO - Make the list of Flight, Accomodation, Transport and Event Booking types more configurable vs in a hard coded query
global class tth_NBA_Generate_TripDisruption {

  global class TripDisruptionInputs {
    @InvocableVariable(label='Traveler Contact ID' description='Traveler ID, if person account use PersonContact.ID' required=true)
    global String travelerContactId;

    @InvocableVariable(label='Trip ID' description='Which trip ID to base booking types from?' required=true)
    global String tripId;
  }

  @InvocableMethod(label='Get Trip Disruption Recommendations'
                     description='Return appropriate Recommendations based on what has been booked on the trip')

   global static List<List<Recommendation>> getTripDisruptionRecommendations(List<TripDisruptionInputs> travelerInfo){
      List<List<Recommendation>> returnedRecList = new List<List<Recommendation>>();
      List<Recommendation> recommendations = new List<Recommendation>();
      List<tth_Booking__c> bookings;

      for (TripDisruptionInputs inputVariables : travelerInfo) {
        try {
          bookings = [SELECT ID, tth_Booking_Type__c FROM tth_Booking__c where tth_Trip__c = :inputVariables.tripId AND tth_Rebooking_Required__c = true];
          System.debug('**** for Trip ' + inputVariables.tripId + ' Found bookings: ' + bookings);
          for(tth_Booking__c curBooking : bookings) {

            System.debug('****** Booking ' + curBooking.ID + ' and Type: ' + curBooking.tth_Booking_Type__c);

            if (curBooking.tth_Booking_Type__c == 'Flight') {
              recommendations.addAll(getFlightRecommendations());

            } else if (curBooking.tth_Booking_Type__c == 'Hotel' || curBooking.tth_Booking_Type__c == 'Accomodation') {
              recommendations.addAll(getAccomRecommendations());

            } else if (curBooking.tth_Booking_Type__c == 'Transport' ||
                        curBooking.tth_Booking_Type__c == 'Bus' ||
                        curBooking.tth_Booking_Type__c == 'Ferry' ||
                        curBooking.tth_Booking_Type__c == 'Rail' ||
                        curBooking.tth_Booking_Type__c == 'Car') {

               recommendations.addAll(getTransportRecommendations());

            } else {
              recommendations.addAll(getEventRecommendations());
            }
          }
       } catch (Exception ex){
          //System.debug('No bookings found for trip ' + inputVariables.tripId);
          //recommendations = new List<Recommendation>();
        }
        returnedRecList.add(recommendations);

      }
      return returnedRecList;
   }


   private static List<Recommendation> getFlightRecommendations() {
     //category__c = RebookFlight
     return getRecommendationsForCategory('RebookFlight');
   }

   private static List<Recommendation> getAccomRecommendations() {
     //category__c = RebookAccomodation
     return getRecommendationsForCategory('RebookAccomodation');
   }

   private static List<Recommendation> getTransportRecommendations() {
     //category__c = RebookTransport
     return getRecommendationsForCategory('RebookTransport');
   }

   private static List<Recommendation> getEventRecommendations() {
     //category__c = RebookEvent
     return getRecommendationsForCategory('RebookEvent');
   }


   private static List<Recommendation> getRecommendationsForCategory(String category) {
     List<Recommendation> recs;
     try {
        recs = [SELECT ID, Name, Description, ActionReference, AcceptanceLabel, RejectionLabel, ImageId, tth_Trip_stage__c, tth_Trip_Sub_stage__c FROM Recommendation WHERE category__c = :category];
        System.debug('Found some ' + category + ' recs: ' + recs);
     } catch (Exception ex) {
       System.debug('No Recommendation found for category ' + category);
        recs = new List<Recommendation>();
     }
     return recs;
   }

}