ido-tth/main/default/objects/Contact/fields/tth_Next_Trip__c.field-meta.xml
<CustomField>
    <fullName>tth_Next_Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the traveler&#39;s next trip/destination?</description>
    <label>Next Trip</label>
    <referenceTo>tth_Trip__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

ido-tth/main/default/objects/tth_Trip__c/tth_Trip__c.object-meta.xml
<CustomObject>
    <description>Top level object that represents all booking channels as well as travel modes for an end to end customer trip</description>
    <label>Trip</label>
    <nameField>
        <displayFormat>TRIP {0}</displayFormat>
        <label>Trip ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ido-tth/main/default/objects/tth_Trip__c/fields/tth_Trip_Destination__c.field-meta.xml
<CustomField>
    <fullName>tth_Trip_Destination__c</fullName>
    <description>What is the destination city for this trip?</description>
    <label>Destination City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ido-tth/main/default/classes/tth_GetNextTripDestination.cls
global class tth_GetNextTripDestination {

  private static String CONTACT_PREIX = '003';
  private static String ACCOUNT_PREFIX = '001';
  private static String CHAT_TRANS_PREFIX = '570';

  @InvocableMethod(label='Next Trip Destination' description='Return the Destination for the Travelers next Trip')
  global static List<String> getNextTripDestination(List<String> recordIDs) {
      List<String> locations = new List<String>();
      //contact 003
      //PersonAccount 001
      String contactId;

      for(String curRecId : recordIDs) {
        if ( curRecId.startsWithIgnoreCase(ACCOUNT_PREFIX) ) {
          System.debug('This is an account/person account record');
          Contact accountContact = [SELECT id FROM Contact WHERE AccountId = :curRecId LIMIT 1];
          contactId = accountContact.ID;
        } else if ( curRecId.startsWithIgnoreCase(CONTACT_PREIX) ) {
          System.debug('This is a contact record');
          contactId = curRecId;
        } else if ( curRecId.startsWithIgnoreCase(CHAT_TRANS_PREFIX) ) {
          System.debug('This is a Live Chat Transcript record');
          LiveChatTranscript chatTrans = [SELECT ContactId FROM LiveChatTranscript WHERE Id = :curRecId LIMIT 1];
          contactId = chatTrans.ContactId;
        } else {
          System.debug('No idea what kind of object this is, I was anticipating either an Account, Contact or LiveChat Transcript');
        }
      }

      tth_Trip__c nextTrip = [SELECT tth_Trip_Destination__c FROM tth_Trip__c where ID IN (SELECT tth_Next_Trip__c FROM Contact WHERE ID = :contactId) LIMIT 1];
      locations.add(nextTrip.tth_Trip_Destination__c);
      return locations;
  }
}