ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/tth_Booking_ReservationSettings__mdt.object-meta.xml
<CustomObject>
    <description>Various settings for the TTH Booking/Reservation functionality.  Includes settings for the following custom objects: Trip, Booking, Reservation</description>
    <label>tth_Booking/ReservationSettings</label>
    <pluralLabel>tth_Booking/ReservationSettings</pluralLabel>
</CustomObject>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/BaggageTriggersDisabled__c.field-meta.xml
<CustomField>
    <fullName>BaggageTriggersDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should be used by all code for triggers on the Baggage object. Enables the ability to disable all via a setting.</description>
    <label>BaggageTriggersDisabled</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/Booking_Reference_Length__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference_Length__c</fullName>
    <defaultValue>9</defaultValue>
    <label>Booking Reference Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/BookingTriggersDisabled__c.field-meta.xml
<CustomField>
    <fullName>BookingTriggersDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should be used by APEX Triggers to check whether they should execute</description>
    <label>BookingTriggersDisabled</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/Generate_Booking_Reference__c.field-meta.xml
<CustomField>
    <fullName>Generate_Booking_Reference__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines whether the Booking Reference field on the Booking custom object should be populated</description>
    <label>Generate Booking Reference</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/Generate_International_Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Generate_International_Ticket_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should the ticket number on the Reservation object be generated?</description>
    <label>Generate International Ticket Number</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/Generate_Record_Locator__c.field-meta.xml
<CustomField>
    <fullName>Generate_Record_Locator__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Should the system auto generate a 6 digit Record Locator?</description>
    <label>Generate Record Locator</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/International_Airline_Number__c.field-meta.xml
<CustomField>
    <fullName>International_Airline_Number__c</fullName>
    <description>Used when generating the Ticket number on the Reservation object. See full list of airlines here: https://www2.arccorp.com/participatingcarriers/#/</description>
    <label>International Airline Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/InternationalTicketLength__c.field-meta.xml
<CustomField>
    <fullName>InternationalTicketLength__c</fullName>
    <defaultValue>10</defaultValue>
    <description>When generating the ticket number on the Reservation, how long should it be NOT including the International Airline Number</description>
    <label>InternationalTicketLength</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/PartyTriggersDisabled__c.field-meta.xml
<CustomField>
    <fullName>PartyTriggersDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should be used by all code for triggers on the Party object. Enables the ability to disable all via a setting.</description>
    <label>PartyTriggersDisabled</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/Record_Locator_Length__c.field-meta.xml
<CustomField>
    <fullName>Record_Locator_Length__c</fullName>
    <defaultValue>6</defaultValue>
    <label>Record Locator Length</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ido-tth/main/default/objects/tth_Booking_ReservationSettings__mdt/fields/TripTriggersDisabled__c.field-meta.xml
<CustomField>
    <fullName>TripTriggersDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should be used by all code for triggers on the Trip object.  Enables the ability to disable all via a setting.</description>
    <label>TripTriggersDisabled</label>
    <type>Checkbox</type>
</CustomField>

ido-tth/main/default/classes/tth_BookingReservationUtils.cls
public class tth_BookingReservationUtils {

  /**
   *
   *
   *
   **/
  public static String generateBookingReference(Integer recordLength) {
      return generateRandomNumber(recordLength);
  }


    /**
     *
     *
     *
     **/
    public static String generateRecordLocator(Integer recordLength) {
        return generateRandomString(recordLength);
    }

    /**
     *
     *
     *
     **/
    public static String generateInternationalTicketNumber(Integer recordLength) {
      return generateRandomNumber(recordLength);
    }

    /**
     *
     *
     *
     **/
    public static tth_Booking_ReservationSettings__mdt getBookingMetadataSettings() {
      tth_Booking_ReservationSettings__mdt metaSettings = null;

      try {
        metaSettings = [SELECT BookingTriggersDisabled__c, TripTriggersDisabled__c,
                        BaggageTriggersDisabled__c, PartyTriggersDisabled__c,
                        Generate_Record_Locator__c, Record_Locator_Length__c,
                        Generate_Booking_Reference__c, Booking_Reference_Length__c,
                        Generate_International_Ticket_Number__c, International_Airline_Number__c, InternationalTicketLength__c
                        FROM tth_Booking_ReservationSettings__mdt
                        WHERE label = 'default'];
      } catch (Exception ex) {
        metaSettings = null;
      }
      return metaSettings;
    }




   /**
     *
     *
     *
     **/
    private static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
        String randStr = '';
        while (randStr.length() < len) {
           Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), 32);
           randStr += chars.substring(idx, idx+1);
        }
        return randStr;
    }


    /**
      *
      *
      *
      **/
    private static String generateRandomNumber(Integer len) {
      final String chars = '1234567890';
      String randStr = '';
      while (randStr.length() < len) {
         Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), 10);
         randStr += chars.substring(idx, idx+1);
      }
      return randStr;
    }

}